require("core.options")
require("core.keymaps")
require("core.plugins")

require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.nvim-treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.telescope")
require("plugins.autopairs")
require("plugins.gitsigns")
require("plugins.comment")
require("plugins.toggleterm")
